name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Configuración para Python (Django)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Ajusta según tu versión

      # Configuración para Node.js (React)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Ajusta según tu versión

      # Instalar dependencias de React
      - name: Install React dependencies
        run: npm install
        working-directory: ./frontend  # Ajusta según tu estructura

      # Instalar dependencias de Django
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # Ejecutar SonarCloud Scan
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          args: >
            -Dsonar.projectKey=freddyandreszambrano_ART_ADORNOS
            -Dsonar.organization=freddyandreszambrano
